########################################################
###THYMELEAF (ThymeleafAutoConfiguration)
########################################################
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML5
#spring.thymeleaf.encoding=UTF-8
# ;charset=<encoding> is added
#spring.thymeleaf.content-type=text/html
# set to false for hot refresh
spring.thymeleaf.cache: false

########################################################
###FREEMARKER (FreeMarkerAutoConfiguration)
########################################################
spring.freemarker:
  allow-request-override: false
  cache: true
  check-template-location: true
  charset: UTF-8
  content-type: text/html
  expose-request-attributes: false
  expose-session-attributes: false
  expose-spring-macro-helpers: false
#spring.freemarker.prefix=
#spring.freemarker.request-context-attribute=
#spring.freemarker.settings.*=
#spring.freemarker.suffix=.ftl
#spring.freemarker.template-loader-path=classpath:/templates/#comma-separatedlist
#spring.freemarker.view-names= #whitelistofviewnamesthatcanberesolved

mybatis:
  mapperLocations: classpath:mybatis/*-mapper.xml
  config: classpath:mybatis/mybatis-conf.xml
  typeAliasesPackage: com.inext.isee
  checkConfigLocation: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isee?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: dinner
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
      serialization:
        INDENT_OUTPUT: true

spring.mobile.devicedelegatingviewresolver.enabled: true
logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.data: DEBUG

spring.http.multipart.enabled: true #默认支持文件上传.
spring.http.multipart.file-size-threshold: 0 #支持文件写入磁盘.
spring.http.multipart.location: # 上传文件的临时目录
spring.http.multipart.max-file-size: 1Mb # 最大支持文件大小
spring.http.multipart.max-request-size: 10Mb # 最大支持请求大小

singleUpload:
  filePath:
    video: "D://test//video//"
    picture: "D://test//picture//"
downLoad:
  filePath:
    video: "D://test//video//"


# JWT
jwt:
  header: Authorization
  secret: iseeSecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"